### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by cssxn** [VirusTotal/yara-python#105]
Run the code below with PyCharm
```
import yara
print yara.compile("rules")
```

I got an error. I tried restart PyCharm with Administrator, It also doesn't work
```
Traceback (most recent call last):
  File "C:/Users/user/PycharmProjects/console/yara_console.py", line 3, in <module>
    print yara.compile("rules")
yara.Error: (13, 'Permission denied')

Process finished with exit code 1
```

**Comment by sbruno** [comment]
Is `rules` a directory? If so try using a yara file instead. 

https://yara.readthedocs.io/en/v3.9.0/yarapython.html#yara.yara.compile

**Comment by cssxn** [comment]
@sbruno Thank Bro, It works！ :+1:
