### ISSUE TITLE
failed to build wheel for yara-python

### ISSUE THREAD

**Issue by YoloHuang** [VirusTotal/yara-python#113]
hello ,I find a bug when I run setup.py ,can you help me ?
![log](https://user-images.githubusercontent.com/16434967/63084857-bed62300-bf7e-11e9-80ac-99655fdae71e.png)

**Comment by Djhomezz** [comment]
I am having the same problem. Internal error 34... I already know there is a subpage for this but it was no help. The image displays the problem I am having. Please help if you know how to solve this. 

![image](https://user-images.githubusercontent.com/7156782/72225285-ae3bd000-3551-11ea-8807-2ecb1bfcb032.png)
