### ISSUE TITLE
v3.10.0 - "nocase" setting does not produce a match, possibly due to incorrect case folding of unicode characters

### ISSUE THREAD

**Issue by ardtex** [VirusTotal/yara-python#114]
Adding "nocase" to a condition does not produce a match when unicode characters(in non-bmp range) are involved. This seems to be a regression from yara-python v3.6.3.

Command to run test -
1. Install yara-python v3.6.3
2. Extract attached zip file, cd into the folder
3. Run - python yara_unicode_test.py sample_data.txt sample_rule.txt
4. Check output (both rules produce a match)
5. Install yara-python v3.10.0
7. Run - python yara_unicode_test.py sample_data.txt sample_rule.txt
8. Check output (rule with nocase condition does not produce a match)

[Test.zip](https://github.com/VirusTotal/yara-python/files/3548328/Test.zip)

**Comment by plusvic** [comment]
Closing this bug and opening https://github.com/VirusTotal/yara/issues/1117

**Comment by plusvic** [comment]
Fixed in https://github.com/VirusTotal/yara/commit/6f3e22d2249fbf4a0a3d842a32564c5ab1325b79
