### ISSUE TITLE
yara-python only reports last compile error, making debugging rules more difficult

### ISSUE THREAD

**Issue by wesinator** [VirusTotal/yara-python#126]
rule that has the following errors:
[test_invalid_nonascii_chars_error.yara.txt](https://github.com/VirusTotal/yara-python/files/4027434/test_invalid_nonascii_chars_error.yara.txt)

```sh
$ yarac test_invalid_nonascii_chars_error.yara /dev/null 
test_invalid_nonascii_chars_error.yara(3): error: non-ascii character
test_invalid_nonascii_chars_error.yara(3): error: syntax error, unexpected end of file, expecting identifier
```

yara-python output only gave the last error, making it harder to debug
`yara.SyntaxError: test_invalid_nonascii_chars_error.yara(3): syntax error, unexpected end of file, expecting identifier`

This is based on a real issue I encountered in a badly formatted rule

**Comment by wxsBSD** [comment]
I actually had a branch which switched yara-python to using the scanner API, but I lost it when my laptop turned into a brick last week. I'll see if I can get another version of it up for review.

**Comment by wesinator** [comment]
> I actually had a branch which switched yara-python to using the scanner API, but I lost it when my laptop turned into a brick last week. I'll see if I can get another version of it up for review.

damn, I'm sorry to hear that. did you lose anything else more important ? 

Thanks !
