### ISSUE TITLE
Feature request: expose ahocorasick in the bindings

### ISSUE THREAD

**Issue by pombredanne** [VirusTotal/yara-python#14]
It would be great to have access to the ahorasick automaton in https://github.com/VirusTotal/yara/blob/b11898bf78336a1ee770e8162a1ac21114ffab88/libyara/ahocorasick.c through this binding

**Comment by pombredanne** [comment]
@plusvic any hint of where I should look first?

**Comment by plusvic** [comment]
Users of YARA shouldn't need to access implementation details. Why do you need to access the Aho-Corasick automaton? How would you use that information?

**Comment by pombredanne** [comment]
@plusvic I would use it as is, as a general purpose multi-string matching library. Now do not bother too much if you do not think it would be useful: I am now contributing to https://github.com/WojciechMula/pyahocorasick which provides the feature nicely and I integrated it in https://github.com/nexB/scancode-toolkit for software license matching.
Thank you for the reply anyway! (and thank __you__ for yara)
You can close this.
