### ISSUE TITLE
setup.py fails with distutils 2.7.11

### ISSUE THREAD

**Issue by joachimmetz** [VirusTotal/yara-python#18]
platform Windows 7 VS 2010
setuptools 18.2
distutils 2.7.11

Error:
```
AssertionError: Should have already checked this
```

Where:
```
distutils\command\bdist_msi.py
```

I think this is related to how setup.py delays defining the Extension()

work around
```
setup.py build bdist_msi
```

**Comment by plusvic** [comment]
I think commit b3e80a1ba48063bb2f774416af906158230b1981 address this issue. Did you tested the latests version in master?

**Comment by joachimmetz** [comment]
thx, I'll give it a try, based on a quick glance of the changes I think that will address the issue.
