### ISSUE TITLE
Request for comment - DEX module

### ISSUE THREAD

**Issue by CalebFenton** [VirusTotal/yara-python#19]
We recently created a module for dalvik executables: https://github.com/rednaga/yara/blob/master/libyara/modules/dex.c

We're using the module for a tool we wrote called apkid, so we have a vested interest in maintaining the module: https://github.com/rednaga/APKiD

Would this be something you're interested in merging into this project? We're not C wizards but we _did_ fuzz the code to make sure there weren't any obvious crashing vulns.

I could make a pull request with this module, but I'm not sure how you'd want it integrated. Either as an optional `--with-dex` compile flag or enabled by default. Please advise.

cc @strazzere

**Comment by wxsBSD** [comment]
I haven't look at the code but this probably belongs in the YARA repo and not YARA-Python. :)

**Comment by CalebFenton** [comment]
Had the wrong repo open. My mistake.
