### ISSUE TITLE
Dynamic linking of yara python module not allowed with CUCKOO / MAGIC

### ISSUE THREAD

**Issue by xambroz** [VirusTotal/yara-python#20]
Hello,
the dynamic linking of the yara python module is not allowed if there is also CUCKOO and MAGIC modules enabled. Is this really necessary? 

The definitions -DMAGIC_MODULE=1 -DCUCKOO_MODULE=1 doesn't seem to be used for anything within yara-python.c and when linking dynamically to libyara still all the testcases from tests.py are working.

Am I missing something or can we get rid of this check?

Thank you
Michal Ambroz

**Comment by plusvic** [comment]
With dynamic linking you can't control whether or not the modules are included during compilations, that's done when you build the library not the yara-python extension. So, --enable-cuckoo and --enable-magic only make sense for static linking, with --dynamic-linking they have no effect. Mixing those options is forbidden to prevent confusion.

**Comment by xambroz** [comment]
OK - understood - thanks for explatantion.
