### ISSUE TITLE
Expose Yara Stats via yara-python

### ISSUE THREAD

**Issue by Derekt2** [VirusTotal/yara-python#224]
Is there a way to expose, via a yara-python function, the stats that are available per ruleset when using the commandline --print-stats on yara?

I'm interested in these stats for profiling the rules by these metrics. Items of value would be 
* size of AC transition table    
* average length of AC matches lists
* number of rules
* number of strings
* number of AC matches
* number of AC matches in root node
There is also "number of AC matches in top 100 longest lists" but that is of arbitrary length and I think could be excluded or optional?

The struct for this is defined in yara.h and types.h struct [here](https://github.com/VirusTotal/yara/blob/d6fc080492912ed34825b4be18ea83f5c5ea6ac9/libyara/include/yara/types.h#L624-L653)

**Comment by plusvic** [comment]
Won't fix due to low demand of this feature.
