### ISSUE TITLE
Publish linux wheels

### ISSUE THREAD

**Issue by florianvazelle** [VirusTotal/yara-python#249]
Hi :wave: 

I would like to know if it would be possible to push the package as a linux wheel in pypi ? Actually, there are only windows wheels.

Accordingly to the [python packaging documentation](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/), there's a github worfklow that lets you build and publish automatically linux wheels on pypi.

If you are interested I can submit a PR :slightly_smiling_face:

**Comment by plusvic** [comment]
That would be a great contribution!

**Comment by florianvazelle** [comment]
I'm closing the issue because my PR has been merged into the main branch.

I'm waiting for the next release :wink:
