### ISSUE TITLE
rule.match(filepath) does not support paths with Chinese characters, Japanese kana, etc

### ISSUE THREAD

**Issue by wwwab123** [VirusTotal/yara-python#252]
As I mentioned in the title, I found that the match() function of the yara-python library does not work properly in special paths containing some languages. I hope it can be compatible with paths containing these languages.

![E4C09399-1D37-49EE-B622-84EF51901663](https://github.com/VirusTotal/yara-python/assets/94147274/7a99e76d-ac88-481f-b089-f6dc3e7f1cd1)
![F58D1186-167C-4C52-B788-C9F886BF4A9C](https://github.com/VirusTotal/yara-python/assets/94147274/f1dadbc8-bc0c-48fd-984e-2012c1fca3af)
![2FAADFA4-92C2-4FBA-8124-1E4BA77BD70D](https://github.com/VirusTotal/yara-python/assets/94147274/3d2de9ec-8882-4a67-8bb5-dd75ded798ec)

**Comment by plusvic** [comment]
Unfortunately this is a limitation in YARA itself, which doesn't support unicode file paths. This limitation is hard to fix, but the alternative is doing something like:

```python
with open('Path/to/file', 'r') as f:
    rule.match(data=f.read())
```
