### ISSUE TITLE
Please distribute source package

### ISSUE THREAD

**Issue by joachimmetz** [VirusTotal/yara-python#253]
Neiter https://github.com/VirusTotal/yara-python/releases or https://pypi.org/project/yara-python/#files provide a source package/distribution, from the latter link:

Source Distributions
No source distribution files available for this release.See tutorial on [generating distribution archives](https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives).

Could you please provide a source package?

**Comment by foundkey** [comment]
I review [publish-to-pypi.yml](https://github.com/VirusTotal/yara-python/blob/master/.github/workflows/publish-to-pypi.yml), it use [pypa/cibuildwheel](https://github.com/pypa/cibuildwheel) to build distribute wheel.

see this [issue 1769](https://github.com/pypa/cibuildwheel/issues/1769), this tool not support build source dist.

**Comment by plusvic** [comment]
Done, I've uploaded a source package for yara-python 4.5.0
