### ISSUE TITLE
yara.compile using an Includes file cannot handle last line without failure

### ISSUE THREAD

**Issue by lukehinds** [VirusTotal/yara-python#260]
The last line in an includes file, will always fail to compile

To recreate, clone the https://github.com/Yara-Rules/rules (or any rule set that uses includes files)

```
python3 -m venv venv
source venv/bin/activate
venv/bin/pip3 install yara-python
Collecting yara-python
  Using cached yara_python-4.5.1-cp311-cp311-macosx_10_9_universal2.whl (414 kB)
Installing collected packages: yara-python
Successfully installed yara-python-4.5.1

venv/bin/python3.11
Python 3.11.3 (main, Apr 19 2023, 18:49:55) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yara
>>> yara.compile("index.yar")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
yara.SyntaxError: ./maldocs/Maldoc_APT10_MenuPass.yar(484): can't open include file: ./webshells/Wshell_fire2013.yar
>>>

tail -n 5 index.yar
include "./webshells/WShell_PHP_Anuna.yar"
include "./webshells/WShell_PHP_in_images.yar"
include "./webshells/WShell_THOR_Webshells.yar"
include "./webshells/Wshell_ChineseSpam.yar"
include "./webshells/Wshell_fire2013.yar"

vi index.yar # remove the last line include "./webshells/Wshell_fire2013.yar"

tail -n 5 index.yar
include "./webshells/WShell_Drupalgeddon2_icos.yar"
include "./webshells/WShell_PHP_Anuna.yar"
include "./webshells/WShell_PHP_in_images.yar"
include "./webshells/WShell_THOR_Webshells.yar"
include "./webshells/Wshell_ChineseSpam.yar"

venv/bin/python3.11
Python 3.11.3 (main, Apr 19 2023, 18:49:55) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yara
>>> yara.compile("index.yar")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
yara.SyntaxError: ./maldocs/Maldoc_APT10_MenuPass.yar(483): can't open include file: ./webshells/Wshell_ChineseSpam.yar
>>> exit()
```

As you can see, whatever is the last line in an includes file will fail to open. I have no idea why ` ./maldocs/Maldoc_APT10_MenuPass.yar(483)` is logged?

**Comment by wxsBSD** [comment]
The error is a bit of a red-herring. I did a binary search to figure out what file is causing the real error and it actually fails at https://github.com/Yara-Rules/rules/blob/master/index.yar#L44 with `yara.SyntaxError: ./maldocs/Maldoc_APT10_MenuPass.yar(27): invalid field name "md5"`. Apparently the version of yara-python I just built to test this doesn't include the crypto bits necessary to use the `hash.md5()` function.

To confirm this is the same problem you're having if you delete everything AFTER the line I referenced above you should get the same error as me. If so, we should investigate why the version you installed via pip3 does not include that. I could have sworn it does, but I also haven't used pip3 for yara-python so I could be wrong.

If you do not get an error then something else is going on and I would suggest you do a binary search in `index.yar` to determine exactly where the failure is in your case and we can debug from there.

**Comment by lukehinds** [comment]
Thanks all, I dropped the index.yar in the end and just loaded everything by directory walking.
