### ISSUE TITLE
Add --with-crypto Yara build option

### ISSUE THREAD

**Issue by CalebFenton** [VirusTotal/yara-python#27]
Yara-python build should also accept `--with-crypto` option in addition to other yara build configuration options like `--enable-cuckoo`.

**Comment by edeca** [comment]
Relates to: https://github.com/VirusTotal/yara-python/issues/28

**Comment by utkonos** [comment]
```
git clone --recursive git@github.com:VirusTotal/yara-python.git
python setup.py build --dynamic-linking
python setup.py install
```
