### ISSUE TITLE
Symbol not found: _yr_compiler_add_file

### ISSUE THREAD

**Issue by r3comp1le** [VirusTotal/yara-python#30]
OSX
Yara Version 3.5
yara-python==3.5.0

`

> > > import yara
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: dlopen(/Library/Python/2.7/site-packages/yara_python-3.5.0-py2.7-macosx-10.11-intel.egg/yara.so, 2): Symbol not found: _yr_compiler_add_file
> > >   Referenced from: /Library/Python/2.7/site-packages/yara_python-3.5.0-py2.7-macosx-10.11-intel.egg/yara.so
> > >   Expected in: flat namespace
> > >  in /Library/Python/2.7/site-packages/yara_python-3.5.0-py2.7-macosx-10.11-intel.egg/yara.so
> > > `

**Comment by plusvic** [comment]
This issue is a bit old, feel free to re-open it if it's persisting in latest version.

**Comment by nahdudenah** [comment]
I'm experiencing the same issue right now:

```python
>>> import yara
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Library/Python/2.7/site-packages/yara_python-3.7.0-py2.7-macosx-10.10-intel.egg/yara.so, 2): Symbol not found: _yr_compiler_add_file
  Referenced from: /Library/Python/2.7/site-packages/yara_python-3.7.0-py2.7-macosx-10.10-intel.egg/yara.so
  Expected in: flat namespace
 in /Library/Python/2.7/site-packages/yara_python-3.7.0-py2.7-macosx-10.10-intel.egg/yara.so

```
Mac OSX 10.10.5, Yara 3.7.0, Yara-python 3.7.0
This is with both yara AND yara-python built from source, not using brew
