### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by jbremer** [VirusTotal/yara-python#33]
Two questions.

1) The binary link for installing `yara-python` on Windows is broken in the documentation.
2) Provided that binaries for Windows have been built in the past, would it be possible to ship those by default (when installing on Windows)? On a plain Windows 7 machine `yara-python` will not install right now as visual studio is missing (which is not necessarily an error, but not everyone will have installed that).

**Comment by maxvonhippel** [comment]
Is this the same issue as [this](https://github.com/VirusTotal/yara-python/issues/15)?

**Comment by jbremer** [comment]
@maxvonhippel Not entirely - I'd like to be able to ship Yara without requiring a compiler in the first place.

**Comment by plusvic** [comment]
In yara-python 3.6.0 we are providing wheel binary packages for Windows, so building on Windows is not required anymore.
