### ISSUE TITLE
Yara failing on Travis CI?

### ISSUE THREAD

**Issue by jbremer** [VirusTotal/yara-python#38]
Hi,

I'm seeing this error more often in the issue list of `yara-python`, however, it would appear those are based on older versions. See, e.g., the following Travis CI report, https://travis-ci.org/jbremer/cuckoo/builds/195577079. On line `2475` you will see a simple test that imports `yara` - and note that `yara-python==3.5.0` was installed through `pip`, while still having the `yr_finalize` import error. I'd very much like to ship Yara with Cuckoo by default, but this regression test failure is preventing me from doing so. Any tips?

Jurriaan

**Comment by plusvic** [comment]
I'll try to reproduce this error. A first try installing yara-python with pip in a clean Ubuntu worked fine. Have you noticed this same error in other environments besides Travis?

**Comment by jbremer** [comment]
Thanks. No, locally it seems to behave fine (which I found to be the odd part). I haven't found any other clues as to why this is happening, though. Please let me know if there's anything additional that I could test to help here.

**Comment by jbremer** [comment]
@plusvic Did you by any chance have the opportunity to check out this potential issue? Thanks :)

**Comment by plusvic** [comment]
@jbremer This issue was caused by setup.py. I've fixed it and should work now. Take a look at the travis.yml I've added to this project: https://github.com/VirusTotal/yara-python/blob/master/.travis.yml

**Comment by jbremer** [comment]
@plusvic Ah, I see, I guess that makes sense :-) Provided I'd like to ship a pinned version number (e.g., `3.5.1`), do you have any plans on doing a new release with this update included?

**Comment by jbremer** [comment]
@plusvic Sorry to bump, but I was wondering if you've considered my request above (a new version with the latest and greatest patches)?
