### ISSUE TITLE
Feature request: Include namespaces in result when matching multiple rule sources

### ISSUE THREAD

**Issue by austinbyers** [VirusTotal/yara-python#39]
```python
import yara
rules = yara.compile(sources={
    'namespace1':'rule dummy { condition: true }',
    'namespace2':'rule dummy { condition: true }',
    'namespace3':'rule dummy2 { condition: true }'}
)
rules.match(data='hello world')  # Returns [dummy, dummy2, dummy]
```

The whole point of the namespaces is to distinguish between the different rules when they may have the same name. Please include the namespaces in the match result, e.g.
```
[namespace1:dummy, namespace2:dummy, namespace3:dummy2]
```
or similar. As it stands, I may have to implement a callback to keep track of which namespaces and rules were matched.

## Environment
I'm running `yara-python v3.5.0`, installed via `pip` on Mac OS X.

**Comment by plutec** [comment]
You can access to namespace using:
```
import yara
rules = yara.compile(sources={
    'namespace1':'rule dummy { condition: true }',
    'namespace2':'rule dummy { condition: true }',
    'namespace3':'rule dummy2 { condition: true }'}
)
results = rules.match(data="hello world")
for result in results:
    print result.namespace # Prints namespace1, namespace2 and namespace3
```
Regards.

**Comment by austinbyers** [comment]
Ah, perfect! I didn't realize the match results were objects. Can we update the [documentation](http://yara.readthedocs.io/en/v3.5.0/yarapython.html#yara.Rules) to include information about the returned `yara.Match` object? Thanks!

**Comment by plusvic** [comment]
`yara.Match` added to documentation in https://github.com/VirusTotal/yara/commit/388f4d00aee4245e7eeb0bf4e4d6261fff86ec5a
