### ISSUE TITLE
Can not allocate memory when build setup in eaba8c1

### ISSUE THREAD

**Issue by gnh1201** [VirusTotal/yara-python#40]
When I did use yara-python released 3.5.0, It have not setup problems and so well.
but, I got memory insufficient error from committed eaba8c1 when build setup
although have enough swap space.

> free -m
>              total       used       free     shared    buffers     cached
> Mem:          3009       1036       1973         12         90        671
> -/+ buffers/cache:        274       2735
> Swap:        13311          0      13311

I know so lack physical memory space of my workspace,
but It is not lack because of all memory space with swap space.

> python setup.py build
> running build
> running build_ext
> building 'yara' extension
> x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_MEMMEM=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -I/usr/include/python2.7 -c yara-python.c -o build/temp.linux-x86_64-2.7/yara-python.o
> yara-python.c: In function ‘yara_callback’:
> yara-python.c:727:60: error: ‘YR_MATCH’ has no member named ‘data_length’
>        object = PyBytes_FromStringAndSize((char*) m->data, m->data_length);
>                                                             ^
> yara-python.c: In function ‘handle_error’:
> yara-python.c:914:10: error: ‘ERROR_INSUFFICIENT_MEMORY’ undeclared (first use in this function)
>      case ERROR_INSUFFICIENT_MEMORY:
>           ^
> yara-python.c:914:10: note: each undeclared identifier is reported only once for each function it appears in
> yara-python.c:940:10: error: ‘ERROR_INVALID_EXTERNAL_VARIABLE_TYPE’ undeclared (first use in this function)
>      case ERROR_INVALID_EXTERNAL_VARIABLE_TYPE:
>           ^
> yara-python.c: In function ‘yara_compile’:
> yara-python.c:1958:31: error: ‘ERROR_INSUFFICIENT_MEMORY’ undeclared (first use in this function)
>          result = handle_error(ERROR_INSUFFICIENT_MEMORY, NULL);
>                                ^
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> root@ubuntu:~/yara-python# python setup.py build
> running build
> running build_ext
> building 'yara' extension
> x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_MEMMEM=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -I/usr/include/python2.7 -c yara-python.c -o build/temp.linux-x86_64-2.7/yara-python.o
> yara-python.c: In function ‘yara_callback’:
> yara-python.c:727:60: error: ‘YR_MATCH’ has no member named ‘data_length’
>        object = PyBytes_FromStringAndSize((char*) m->data, m->data_length);
>                                                             ^
> yara-python.c: In function ‘handle_error’:
> yara-python.c:914:10: error: ‘ERROR_INSUFFICIENT_MEMORY’ undeclared (first use in this function)
>      case ERROR_INSUFFICIENT_MEMORY:
>           ^
> yara-python.c:914:10: note: each undeclared identifier is reported only once for each function it appears in
> yara-python.c:940:10: error: ‘ERROR_INVALID_EXTERNAL_VARIABLE_TYPE’ undeclared (first use in this function)
>      case ERROR_INVALID_EXTERNAL_VARIABLE_TYPE:
>           ^
> yara-python.c: In function ‘yara_compile’:
> yara-python.c:1958:31: error: ‘ERROR_INSUFFICIENT_MEMORY’ undeclared (first use in this function)
>          result = handle_error(ERROR_INSUFFICIENT_MEMORY, NULL);
>                                ^
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

It is occurred from return null(no rules) of pyobject_new.
I can not know reason why not allocate memory by pyobject_new in master(eaba8c1) source code.

**Comment by plusvic** [comment]
The build didn't failed because of insufficient memory, the issue was caused by a change in the `ERROR_INSUFFICIENT_MEMORY` define. It was renamed from `ERROR_INSUFICIENT_MEMORY` to `ERROR_INSUFFICIENT_MEMORY` (notice the double F). But this was already solved.
