### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'libeay64.lib'

### ISSUE THREAD

**Issue by whisperzzzz** [VirusTotal/yara-python#41]
Here's the log while executing "pip install yara-python":

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:yara/windows/lib /LIBPATH:C:\Python3\libs /LIBPATH:C:\Python3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\um\x64" advapi32.lib user32.lib libeay64.lib /EXPORT:PyInit_yara build\temp.win-amd64-3.6\Release\yara-python.obj build\temp.win-amd64-3.6\Release\yara\libyara\ahocorasick.obj build\temp.win-amd64-3.6\Release\yara\libyara\arena.obj build\temp.win-amd64-3.6\Release\yara\libyara\atoms.obj build\temp.win-amd64-3.6\Release\yara\libyara\compiler.obj build\temp.win-amd64-3.6\Release\yara\libyara\exec.obj build\temp.win-amd64-3.6\Release\yara\libyara\exefiles.obj build\temp.win-amd64-3.6\Release\yara\libyara\filemap.obj build\temp.win-amd64-3.6\Release\yara\libyara\grammar.obj build\temp.win-amd64-3.6\Release\yara\libyara\hash.obj build\temp.win-amd64-3.6\Release\yara\libyara\hex_grammar.obj build\temp.win-amd64-3.6\Release\yara\libyara\hex_lexer.obj build\temp.win-amd64-3.6\Release\yara\libyara\lexer.obj build\temp.win-amd64-3.6\Release\yara\libyara\libyara.obj build\temp.win-amd64-3.6\Release\yara\libyara\mem.obj build\temp.win-amd64-3.6\Release\yara\libyara\modules.obj build\temp.win-amd64-3.6\Release\yara\libyara\object.obj build\temp.win-amd64-3.6\Release\yara\libyara\parser.obj build\temp.win-amd64-3.6\Release\yara\libyara\proc.obj build\temp.win-amd64-3.6\Release\yara\libyara\re.obj build\temp.win-amd64-3.6\Release\yara\libyara\re_grammar.obj build\temp.win-amd64-3.6\Release\yara\libyara\re_lexer.obj build\temp.win-amd64-3.6\Release\yara\libyara\rules.obj build\temp.win-amd64-3.6\Release\yara\libyara\scan.obj build\temp.win-amd64-3.6\Release\yara\libyara\sizedstr.obj build\temp.win-amd64-3.6\Release\yara\libyara\stream.obj build\temp.win-amd64-3.6\Release\yara\libyara\strutils.obj build\temp.win-amd64-3.6\Release\yara\libyara\threading.obj build\temp.win-amd64-3.6\Release\yara\libyara\modules\demo.obj build\temp.win-amd64-3.6\Release\yara\libyara\modules\elf.obj build\temp.win-amd64-3.6\Release\yara\libyara\modules\hash.obj build\temp.win-amd64-3.6\Release\yara\libyara\modules\math.obj build\temp.win-amd64-3.6\Release\yara\libyara\modules\pe.obj build\temp.win-amd64-3.6\Release\yara\libyara\modules\tests.obj /OUT:build\lib.win-amd64-3.6\yara.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\yara.cp36-win_amd64.lib

  **LINK : fatal error LNK1181: cannot open input file 'libeay64.lib'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1181**

I had openssl installed and specified it in the PATH. The error code 1181 seems like there exist spaces in the path of the linker. Is there a way to fix this problem?

**Comment by plusvic** [comment]
In yara-python 3.6.0 we are providing binary wheels for Windows.
