### ISSUE TITLE
Add a flag to the match function which indicates if you want your callback called for matches, non-matches or both

### ISSUE THREAD

**Issue by TofBaasken** [VirusTotal/yara-python#42]
When matching a lot of files against a lot of files with yara python , the callback function gets called every time , match or no match , which creates a lot of overhead if you're only interested in the matches.
Would it be possible to provide an option where you can specify whether you want your callback called for matches, non-matches or both? I think performance could increase a lot ...

**Comment by plusvic** [comment]
Already implemented in #66.
