### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by scudette** [VirusTotal/yara-python#5]
Is this supposed to be working yet? 

```
$ pip install -I yara-python
Downloading/unpacking yara-python
  Could not find any downloads that satisfy the requirement yara-python
Cleaning up...
No distributions at all found for yara-python
Storing debug log for failure in /home/scudette/.pip/pip.log
```

Also when installing by hand it seems to make an empty package. Even after `git submodule init/update`.

**Comment by plusvic** [comment]
@scudette this issue is a bit old, with the latest version (3.6) the installation should work. Feel free to re-open this issue if it still applies.
