### ISSUE TITLE
Compiled Rules file is not handled in yara-python

### ISSUE THREAD

**Issue by rainaashutosh** [VirusTotal/yara-python#50]
Issue:
yara.load method is throwing an unknown error when yara compiled file is passed on as input.
I have tried using both filepath and file args in method but it shows the same error

![yara1](https://user-images.githubusercontent.com/16841220/27729490-b3c631c4-5da3-11e7-9117-bd0735356b83.png)

![yara2](https://user-images.githubusercontent.com/16841220/27729581-13da734a-5da4-11e7-841d-97973616cfa4.png)

**Comment by plusvic** [comment]
That's `ERROR_UNSUPPORTED_FILE_VERSION`, which means that the compiled file was generated by a different version of YARA. It should work fine if you compile the rules with yara-python too.

**Comment by plusvic** [comment]
I'm adding a more meaningful error message though.

**Comment by plusvic** [comment]
Already fixed.
