### ISSUE TITLE
AttributeError: 'module' object has no attribute 'compile'

### ISSUE THREAD

**Issue by mylamour** [VirusTotal/yara-python#51]
```
Traceback (most recent call last):
  File "yara.py", line 5, in <module>
    import yara
  File "/home/mour/working/script/yara.py", line 8, in <module>
    rules = yara.compile("./php.yar")
AttributeError: 'module' object has no attribute 'compile'
```
I don't know what's wrong with it, No matter what, I use `pip install yara-python` also compile from source code, always was wrong. 
```
conda:  python version: 3.6
yara lastst version compile from source code
```

**Comment by plusvic** [comment]
Can you put a `print dir(yara)` on the line just before `yara.compile` and tell me what it prints out?

**Comment by mylamour** [comment]
```
import yara
print(dir(yara))
```
This is the result copy from the terminal 
```
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'gevent', 'monkey', 'pool', 'yara']
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'gevent', 'monkey', 'os', 'pool', 'subprocess', 'yara']

```

**Comment by plutec** [comment]
Do you have any yara.py file in the same folder? Maybe instead of load the
module you're loading that local file.

**Comment by plusvic** [comment]
@mylamour rename your Python script from `yara` to something else. What it's happening here is that Python is loading your own `yara.py` instead of the yara module.
