### ISSUE TITLE
Cannot use yara-python to compile rules when adding new modules(Androguard or cuckoo) in yara

### ISSUE THREAD

**Issue by maoqyhz** [VirusTotal/yara-python#52]
I want to use **Androguard** and **cuckoo** in yara, so i recompile yara. And in command-line, it can work well, But when i use yara-python, it raise some error, just like.
```
rule = yara.compile(source='import "cuckoo"')
yara.SyntaxError: line 1: unknown module "cuckoo"
```
so how to fix it?

**Comment by plusvic** [comment]
You must build yara-python with:
```
python setup.py --enable-cuckoo
```

**Comment by maoqyhz** [comment]
I using pip to uninstall yara-python. `sudo pip uninstall yara-python`. Then i rebuild and install it .
```
python setup.py build --enable-cuckoo
sudo python setup.py install
```

But the error still existed.

**Comment by maoqyhz** [comment]
thinks a lot. I clean all of install file, and reinstall it. no error!
