### ISSUE TITLE
do not work with --dynamic-linking

### ISSUE THREAD

**Issue by nanshihui** [VirusTotal/yara-python#76]
when i typed with 'sudo python setup.py install --dynamic-linking'.
it return 'error: option --dynamic-linking not recognized'

**Comment by cmderpt** [comment]
I think I have same issue as you. Instead of install with --dynamic-link, I try to install without --dynamic-linking and then I just remove `yara.so` in `/usr/local/lib/python2.7/dist-packages` or where is installed by pip

**Comment by plusvic** [comment]
Try `python setup.py build --dynamic-linking && sudo python setup.py install`

**Comment by nanshihui** [comment]
thanks a lot
