### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by JScharloo** [VirusTotal/yara-python#79]
When using this library for fast multi-threaded file analysis, some internal datastructures in the match functionality are not garbage collected properly. Weak references remain in system memory. I have not yet found the source of this issue within the module source code itself, but when running the library over several thousand files you can see that the memory builds up. I have eliminated every other possible cause.

When I find more I will let you know and/or make a pull request. Until then please be notified.

**Comment by JScharloo** [comment]
I have been running tests with passing either raw data or pointing it to a filepath. I am not quite sure yet if the issue is in the wrapper or the underlying yara module. Right now I am thinking of either spawining seperate processes for the match functionality which can then be disposed of, or dropping this library all together and using system calls due to the fact that YARA modules are also not supported during compilation of rules.

**Comment by plusvic** [comment]
Any update on this? I'm curious if you finally found any memory leaks. We run YARA for weeks using [go-yara](https://github.com/hillu/go-yara) and so far haven't found any memory leaks in the library itself. So my guess is that the memory leak, if any, should be yara-python.

**Comment by JScharloo** [comment]
I ended up dumping yara-python and making a small wrapper using system calls. The leak is definitely in yara-python. It has trouble garbage collecting used processes. Manual GC doesn't help enough.

**Comment by mephos** [comment]
Think I've nailed it

https://github.com/VirusTotal/yara-python/blob/master/yara-python.c#L50

in **Python 3,** `PY_STRING_TO_C` uses` PyUnicode_AsEncodedString`
This function allocates a new python object to store the **bytes** representation of the string

The result is fed to `PyBytes_AsString` which is used to get a` char *` to the internal buffer of the bytes object

(no problem in **python 2** as it uses only `PyString_AsString `which doesn't allocate a new object)


This **bytes** object is never released (the reference count is never decreased, the pointer to the actual object is also "lost" in the macro as it's fed to `PyBytes_AsString` and never "saved" anywhere)
You can see how it might be done at http://agentzh.org/misc/code/gdb/python/py-utils.c.html (line 111)

the `PY_STRING_TO_C`  macro is, among other things,  used in `process_match_externals` 

I've tried using the `match()` function without using **external** variables and there was no leak

steps to reproduce (in a loop ) :

 `
     rules.match('c:\\windows\\system32\\calc.exe', externals = {'aa':'aa'*1024*1024})
`

memory usage should grow steadily

the `PY_STRING_TO_C`  macro is also used in a few other places (when compiling rules for instance)  and induce leaks but it's not as visible as calling `xxx.matches `repeatedly on different files

**Comment by plusvic** [comment]
Good job @mephos! Please can you confirm that #94 fixes the issue and everything else works fine for you?

**Comment by mephos** [comment]
patch looks good to me!

thanks @plusvic!
(could you bump the version to 3.8.2 and push the new version to pypi as well? thx)
