### ISSUE TITLE
Segfault reporting invalid rule string

### ISSUE THREAD

**Issue by jimrthy** [VirusTotal/yara-python#82]
I'm trying to get yara-python 3.7.0 working with the cuckoo module.

I followed the instructions to clone the repo recursively, run `python setup.py build --enable-cuckoo` and `python setup.py install`.

Now I'm trying to get some basic tests running.

I'm setting up a string with a simple condition, calling `yara.compile(source=foo)`, setting up a dict with my cuckoo report, and then calling `rule.match(data='MALWARE', module_data=modules_dict)`

yr_rules_scan_mem returns error code 6. That part shouldn't matter much.

Line 1517 calls `handle_error(error, filepath)`

That takes us down to the call to PyErr_Format on line 934, which causes a segfault because the parameter `extra` is NULL.

I'm not sure what the proper fix would be here. Switching to `handle_error(error, filepath || data)` seems like the quickest/easiest.

**Comment by plusvic** [comment]
Fixed via https://github.com/VirusTotal/yara/commit/09988bc30d0dbf09721099ce61f99f936694f19f
