### ISSUE TITLE
Trouble getting yara-python with androguard to detect

### ISSUE THREAD

**Issue by marvinsun09** [VirusTotal/yara-python#83]
Assuming I installed everything correctly. I am having problems triggering the yara rule with androguard and I'm not seeing errors.

```
<python script>
import yara
import json

jsonFile = open("yara_report.json")
jsonData = jsonFile.read()
JSON = json.loads(jsonData)
rules = yara.compile("rule.yar")
matches = rules.match("yara_report.json", modules_data=JSON)
print(matches)

<rule.yar>
import "androguard" 

rule byAndroguard { 
	condition: 
		androguard.package_name("com.palasandoreki.hsa2")
}

rule byFile 
{
	strings:
		$str = "com.palasandoreki.hsa2" nocase	

	condition:
		$str
}
```
The yara_report is downloaded from Koodous. I'm assuming the report JSON is loaded via modules_data? I also loaded the JSON as a file for testing purposes. 

After testing, the byFile rule triggers since the string was found in the JSON, but the byAndroguard rule didn't trigger. Not sure if I'm doing this properly. Thanks!

**Comment by ddurando** [comment]
reading from yara-python docs:

> **modules_data** _(dict)_ – Dictionary with additional data to modules. Keys are module names and values are _bytes_ objects containing the additional data.

You need to pass a dictionary with key equal to androguard (the -x parameter if yara was run from command line) and a bytes object as value. 
```python
json_obj = io.open(json_file_path, "rb").read() 
matches = rules.match(file, modules_data={"androguard": json_obj})
```
Hope this helps

**Comment by marvinsun09** [comment]
That's it! It works, thanks!

**Comment by jamesstickmares** [comment]
Could you provide a fully working example please? I'm not able to match the rule

**Comment by ddurando** [comment]
Something like this should work

`
import yara
import io

rules = yara.compile("rule.yar")
json_obj = io.open(json_file_path, "rb").read() 
matches = rules.match(file, modules_data={"androguard": json_obj})
print(matches)`

**Comment by roopeshiitd** [comment]
Can you guys please tell me how did you compile yara-python with androguard? I'm trying on windows but couldn't find any lead.

**Comment by roopeshiitd** [comment]
Actually Im getting the below error when I do python setup.py build
running build
running build_ext
creating Users
error: [WinError 6] The handle is invalid
