### ISSUE TITLE
Failed to import yara module.

### ISSUE THREAD

**Issue by rbshadow** [VirusTotal/yara-python#86]
Whenever I try to import yara module it comes from the mentioned location. And I failed to access compile function. Where is the problem?

![oo](https://user-images.githubusercontent.com/12114842/39505604-42b3d372-4df5-11e8-8c7b-0e99d9e184d5.png)

**Comment by rbshadow** [comment]
No sir. "yara.py" is another file and that's not problem. Generally after installed yara and yara-python we can access yara module as built-in module. (I have tested several times). But in many times this problem arise and yara module shows wrong location.

**Comment by plutec** [comment]
Could you share with us the files tree where ttt.py is located?

**Comment by rbshadow** [comment]
Sir, problem is fixed. I built from source earlier and maybe there was some problems. After using pip problem is solved. Thank you.
