### ISSUE TITLE
3.7.1 release

### ISSUE THREAD

**Issue by austinbyers** [VirusTotal/yara-python#87]
Can we get v3.7.1 of `yara-python` released to match the version of YARA? The commit is already in master, we just need a release.

I think I'm running into problems because my version of YARA is 3.7.1, but when I `pip install yara-python` in different environments, `yara-python` builds an older version of YARA.

**Comment by peixotorms** [comment]
I also get 3.7.0 on centos

**Comment by plusvic** [comment]
Version 3.8.0 of both `yara` and `yara-python` has been released.
