### ISSUE TITLE
YARA on Pypi

### ISSUE THREAD

**Issue by flamableconcrete** [VirusTotal/yara-python#9]
It looks like you have pushed this version up to https://testpypi.python.org, but someone else ( mjdorma/ Michael Dorman) is the owner/maintainer on pypi. Is there any push to get this consolidated/figured out so YARA 3.4 can be for the masses? Thanks!

https://pypi.python.org/pypi/yara
https://testpypi.python.org/pypi/yara-python/3.4.4

**Comment by pombredanne** [comment]
@flamableconcrete On Pypi yara is a c-types wrapper to Yara, not from Yara or @pluvic proper.
And yara-python is this code alright and fairly up to date. So what is the issue?

**Comment by plusvic** [comment]
As @pombredanne said, `yara` was used for a c-types based wrapper implemented by Michael Dorman. The official Python module is `yara-python`.
