### ISSUE TITLE
Invalid field name "imphash" on 3.8.1

### ISSUE THREAD

**Issue by ricardo-dias** [VirusTotal/yara-python#97]
The latest version of yara-python is unable to compile rules with the pe.imphash():

>>> yara.YARA_VERSION
'3.8.1'
>>> rule = yara.compile(source='import "pe" rule my_imphash {condition: pe.imphash()=="eecc824da5b175f530705611127a6b41"}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
yara.SyntaxError: line 1: invalid field name "imphash"

The same rule is parsed without problems by the yara binary of the same version.

Thanks in advance.

**Comment by wxsBSD** [comment]
This is because of how you built yara-python. Did you build from source? If so, how did you clone the repo and build it. Can you provide build logs?

**Comment by ricardo-dias** [comment]
You were right, the problem was due to problems when building. Rebuilding from source solved the problem. Thanks.
